import { notePinKey } from "./noteKey";

export const scadGen = (notes) => {
    const generatePins = (pins, side) => {
        //get the total number opf beats, every array index should be the same length
        const totalBeats = pins[0].length;
        //get the spacing needed to evenly space all notes around the circle
        const space = 360 / totalBeats;
        let output = ``;

        for (let i = 0; i < 16; i++) {
            for (let j = 0; j < totalBeats; j++) {
                if (pins[i][j]) {
                    output += `
				pin(${notePinKey[i]},${space * j},${side});`;
                }
            }
        }
        return output;
    };

    return {
        text: `
/* This file has been generated by Chris's Fisher Price Record Maker
 * This file was taken from  Fred's Fisher Price Record Creator. Thanks for all your hard work Fred!
 * http://www.instructables.com/id/3D-printing-records-for-a-Fisher-Price-toy-record-/
 *
 * Press F6 to view your model in OpenSCAD
 * Then you cn export as STL for printing
 */

// Configuration

$fn = 360;
holeClearance = 0.4;

hStock = 4.6;
rStock = 121.1 / 2;
rCenterHole = (6.55 + holeClearance) / 2;
oDrive = 21.8;
rDrive = (3.1 + holeClearance) / 2;
hInset = 1.6; // I measure ~1.4, but erring high to ensure we ride on the flats, not the inset.
rInset = 50.9 / 2;
hGroove = 1.6; // I measure ~1.3, but we want to err high so the tone arm doesn't jump as the gears rotate.
overlap = 0.2;

hasSecondSide = 1;

// Some very useful code by HarlanDMii
// http://www.thingiverse.com/thing:16193
// Disabled as some people had problems with it
// Uncomment to create title 
// If you have trouble, download https://github.com/rohieb/Write.scad and copy all the files to the same directory as this SCAD file
// include <write.scad>

// Tone arm geometry, so that chords are staggered appropriately to not sound arpeggiated.
toneArmPivotPosition = [96, 71];
toneArmLength = 113.5;
toneArmTrackSpacing = 27.8 / 20;
toneArmNumTracks = 22;
// The above was measured, and then this is fudged until the pins line up with the grooves.
toneArmAngle = 237.6;

// Create disc
module createDisc() {
	union() {

		createBlank();

		// Add the notes for the song. This part is dynamically generated.
		// Autogenerated pins for music tracks
		${generatePins(notes[0], 0)}
	

		title("${notes[0][16]}",0);

		// Autogenerated pins for music tracks
		${generatePins(notes[1], 1)}


		title("${notes[1][16]}",1);


	}
}

// Create the blank, ready for dynamically added pins
module createBlank() {

	difference() {
	
		rotate_extrude(convexity=12) {
			difference() {
				// stock
				square([rStock, hStock]);

				// top cutout
				translate([0, hStock - hInset]) square([rInset, hInset + overlap]);

				// Bottom cutout lets the disc sit flatter, but some printers my struggle with the overhang
				translate([0, -overlap]) square([rInset, hInset + overlap]);

				// Centre hole		
				translate([0, 0]) square([rCenterHole, hStock]);

				// Tracks - each one for two notes
				track(28.15, 0);
				track(30.89, 0);
				track(33.71, 0);
				track(36.425, 0);
				track(39.225, 0);
				track(42, 0);
				track(44.825, 0);
				track(47.555, 0);
				track(50.315, 0);
				track(53.11, 0);
				track(55.9, 0);

				if (hasSecondSide > 0) {
					track(28.15, 1);
					track(30.89, 1);
					track(33.71, 1);
					track(36.425, 1);
					track(39.225, 1);
					track(42, 1);
					track(44.825, 1);
					track(47.555, 1);
					track(50.315, 1);
					track(53.11, 1);
					track(55.9, 1);
				}
			}
		}	

		// Drive holes
		translate(v = [0,oDrive,0]) { cylinder(h=hStock, r=rDrive); }
		translate(v = [0,-oDrive,0]) { cylinder(h=hStock, r=rDrive); }
		translate(v = [oDrive,0,0]) { cylinder(h=hStock, r=rDrive); }
		translate(v = [-oDrive,0,0]) { cylinder(h=hStock, r=rDrive); }		
	}
}

// Negative for a double track (2d, to be rotate_extruded)
module track(inner, onSecondSide) {
	if (onSecondSide > 0) {
		translate(v = [0,-overlap]) {
			difference() {
				square(size=[inner+2, hGroove+overlap]);
				square(size=[inner,hGroove+overlap]);
			}
		}
	}
	else {
		translate(v = [0,hStock-hGroove]) {
			difference() {
				square(size=[inner+2, hGroove+overlap]);
				square(size=[inner, hGroove+overlap]);
			}
		}
	}
}

// Create a pin at a certain angle
module pin(inner, outer, angle, onSecondSide)
{
	pinWidth = .8;

	// could modify the JS to pass this in
	trackIndex = floor(toneArmNumTracks * ((inner + outer) / 2 - 27.95) / (58.1 - 27.95));

	translate(onSecondSide * [0, 0, hStock / 2])
	rotate(onSecondSide * [180, 0, 0])
	translate(onSecondSide * [0, 0, -hStock / 2])	
	rotate(angle)
	translate(toneArmPivotPosition)
	rotate(toneArmAngle)
	translate([toneArmLength - pinWidth, (trackIndex - toneArmNumTracks / 2) * toneArmTrackSpacing, hStock - hGroove - overlap])
	#cube(size = [pinWidth, toneArmTrackSpacing, hGroove + overlap]);
}

// Add text
module title(text, onSecondSide)
{
// Disabled as some people had trouble with it
// Uncomment to create title 
	//if (onSecondSide>0)
	//	writecylinder(text, [0,0,-hInset], radius=20, height=hStock-hInset, h=3, t=hInset, face="bottom");
	//else
		//writecylinder(text, [0,0,0], radius=20, height=hStock-hInset, h=3, t=hInset, face="top");
}

// Do the work
createDisc();
`,
        title: `${notes[0][16]} & ${notes[1][16]}`,
    };
};
